### ISSUE TITLE
Attachments seem to be missing

### ISSUE THREAD

**Issue by dune73** [coreruleset/website#13]
Walter's obituary links to his family's obituary as PDF. Yet it can't be found.

https://coreruleset.github.io/images/2024/02/Digitale-rouwkaart-Walter-Hop.pdf

**Comment by fzipi** [comment]
No worries, the file is there. Sometimes links need to be remade, because they are absoute vs. relative. 

For example, the end url will be that `/images...`, but because we are in the development deployment, the website sits at `coreruleset.github.io/website` instead of `coreruleset.org`. Because of that I've been changing links to be independent of that using the `{{< ref "..." >}}` function. Let me fix it so you can see.
