### ISSUE TITLE
Links to blog posts still broken - please fix

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/website#71]
Hi,

The following links to blog posts *work on the old website*, but are still broken on the new website:

- [ ] 19 (https://coreruleset.org/20230503/a-brief-report-on-the-crs-community-summit-2023/)
- [ ] 23 (https://coreruleset.org/20230117/meet-the-crs-team-franzi-the-puzzle-loving-hard-worker-with-a-mission/)
- [ ] 34 (https://coreruleset.org/20220308/crs-names-felipe-zipitria-as-third-co-lead/)
- [ ] 38 (https://coreruleset.org/20220112/crs-plugin-mechanism/)
- [ ] 53 (https://coreruleset.org/20201228/owasp-modsecurity-core-rule-set-v3-3-1-release-candidate-1-available/)
- [x] 66 (https://coreruleset.org/20190903/announcement-owasp-modsecurity-core-rule-set-version-3-2-0-rc2/)
- [ ] 67 (https://coreruleset.org/20190826/optimizing-regular-expressions/)
- [ ] 78 (https://coreruleset.org/20181003/owasp-crs-slack/)
- [ ] 93 (https://coreruleset.org/20180211/crs-project-news-february-208/)
- [ ] 94 (https://coreruleset.org/20180112/crs-project-new-january-2018/)
- [ ] 98 (https://coreruleset.org/20171207/core-rule-set-project-winning-osbar-award/)
- [ ] 100 (https://coreruleset.org/20171121/top-5-ways-crs-can-help-you-fight-owasp-top-10/)
- [ ] 113 (https://coreruleset.org/20170727/crs3-presentation-owasp-london/)

If it's a time issue then please document the fix procedure and I will fix these myself.

Thanks.

**Comment by azurit** [comment]
Are those links really correct? These pages on current website are working fine but are accessible under the different URL. What exactly is the problem here? Is it that the URLs on new website changed so we need to rename them back so they will be accessible using old URL and NOT accessible on the current URL?

**Comment by fzipi** [comment]
The problem is: wordpress used to present permanent URLs with a different format. Hugo (the new software) creates the links in a different way, skipping some characters, hence it affects the final permanent URL. Because those urls might be cross posted in other places in the world, they will get a 404 when someone goes to a third party page, e.g. a twitter link.

So the idea is to have the urls _exactly as they were_ so we don't affect people. It doesn't matter for *new* posts, just for old stuff.
